[project]
name = "sba-928-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=5.1.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "peft>=0.21.2",
    "pyreadstat>=1.3.6",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]

[project.scripts]
sba-928-new = "sba_928_new:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
